### PR TITLE
created created new readme based on old one and added contributing.md…

### PR DESCRIPTION
**Pull request by linnal86**
updated the readme based on the old Readme.md. I kepted it just in case for now. 
Please review my changes and let me know if anything is unclear if it's not what we're looking for in terms of readme documentation. 
Any feeback will be helpful.
Thanks!

### CODE REVIEW

**Comment by laurafeeney** [comment]
@linnali577  Thanks for getting started with this work! I haven't looked at this front level readme (ever) so just getting familiar with it. I have a few comments before merging...

- The previous suggestion for documentation was the [wiki](https://github.com/codeforboston/clean-slate/wiki) though it makes sense to at least point people in the right place in the readme. 
- I don't think the readme is the right place for the 'current stage', at least not at this time, since this project has a whole app team as well. It would be easiest to maintain if this were a bit more static, and pointed people to eg the project board to see what tasks are outstanding/in progress.  
- overview of github files - i'm not familiar with any of the folders bgesides data and analysis. This might be best addressed in a full team meeting
- If I'm reading the markup right, you're changing the high level goal to be analyzing data. I would leave teh goals as-is, or discuss with the full team on Tuesday. The app team doesn't use the data, they're building an app to help peple understand if they're eligible. So putting 'analyze data' in the header of the goals woudnt be accurate for that team. 

Data questions!
- we've been numbering these close-ish to the original  numbering, though with some inconsistency. (1, 2a, 2b, or sometimes 1, 2, 2a). But I think just 1-5 is probably easier and worth the conversion
- clarifying the interpretation of these. 
1. I would say "count the number" not "find" the individuals, since we're concerned with aggregate #'s not exaclty who's who. -

- Otherwise I think this is restated more clearly than the original.
For the other questions, could start with: "How many individuals would be eligible for expungement if the eligibility criteria were:" And note that after Q1, everything is varied by _incident_ (which may comprise 1 or more offenses/charges)
2. Individual has only one incident (may have multiple offenses/charges within that), with none of the offenses on the list of ineligible offenses
3. All offenses/charges are eligible for expungement except those related to sex or murder. How does this vary if individuals must have only a single incident vs may have multiple incidents? 
4. Offenses are ineligible if they were found guilty and were on the list of ineligible offenses. How does this vary if individuals must have only a single incident vs may have multiple incidents? 
5. Offenses are ineligible if they were found guilty and are related to murder or sex. How does this vary if individuals must have only a single incident vs may have multiple incidents?

Contributing:
There are different norms for app vs data team. I think app team uses forks and pull requests. For the data team, if people are contributing frequently / have attended a few Tuesday meetings, we can give them direct write access.

**Comment by linnali577** [comment]
Updated the readme again. 
Please review the changes and let me know what else I should fix on the readme document.

**Comment by linnali577** [comment]
I've edited how the data folder is organized. 
deleted the docs folder - all add this to the google drive
Please look over the changes and let me know if anything needs to be fixed.

**Comment by laurafeeney** [comment]
Making some comments as I look through things. I think it would be helpful to get thoughts from the broader team before making substantial changes to the main readme, and as a head's up about other restructuring. 

I made some specific comments on the edited wiki/readme pages that should show up above. Beyond that, some other probably randomly sorted comments:

- is the data overview meant as just a preliminary file, that we'd add more narrative or description to? 
- i'm struggling conceptually with the data folder organization, particularly the separation of crime v prosecution categories. 
- more of a "to do": the Data wiki [Expungement Analysis](https://github.com/codeforboston/clean-slate/wiki/Data:-Expungement-Analysis) could use some updating -- could be a home for the main q's were trying to answer from #152 , updating over the older version.

**Comment by linnali577** [comment]
1. What concerns do you have regarding the main readme? We can ask the broader team about them and we can ask them to look over it before we update.
2. Yes, you would add to the data overview with more descriptions. What I added is just starter information on the datasets
3. How do you suggest organizing the data folder? We can put the crime and prosecution files together or organize some other way if you have a better way of organizing it.

**Comment by laurafeeney** [comment]
> 1. What concerns do you have regarding the main readme? We can ask the broader team about them and we can ask them to look over it before we update.

No concerns, just seems worth giving a head's up since it's the front page and since the new readme describes the app team and their goals and where to start with their stuff as well as the data side. 

> 2. Yes, you would add to the data overview with more descriptions. What I added is just starter information on the datasets
> 3. How do you suggest organizing the data folder? We can put the crime and prosecution files together or organize some other way if you have a better way of organizing it.

My suggestion...

- Expungement eligibility crosswalks (*maybe 'offense_eligibility' or 'offense_categories'? i'm not sure what's descriptive enough without being super long*)
-- Expungecategories*.csv
-- missing_expungeability*.csv
-- prosecution_charges*.csv (*except I propose deleting prosecution_northwestern.csv and prosecution_suffolk.csv*)
-- [a couple of other csv/google sheets currently on Drive that could go here instead]]

- Raw prosecution data
-- nw
-- suff.csv
-- some kind of placeholder / pointer to the original middlesex file, unless someone else can upload it

- Processed prosecution data
-- merged_*.csv

- FBI data (your proposal make sense)


I generally like the raw vs processed vs clean delineation. I think where this breaks down is the crosswalk type information (all the expungecategories etc), where none of it is really "raw" or "processed". The other place that it breaks down is when we don't follow the structure and just throw everything in willy nilly. Perhaps this category of data based approach will be more intuitive.

**Comment by laurafeeney** [comment]
@jeremylang would be great to hear your thoughts on the main page readme, and perhaps wiki stuff

**Comment by linnal86** [comment]
Not changing ReadMe for now. Focusing on reorganizing folder structure.

**Pull request closed without merging**
